version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # Si tu entrypoint es otro, adaptalo (ej: ./mvnw spring-boot:run)
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev